### ISSUE TITLE
bug: ARM64 image contains wrong binary

### ISSUE THREAD

**Issue by Daedaluz** [l7mp/stunner-auth-service#4]
The arm64 image seems faulty.
Deploying the gateway operator on an arm64 cluster results in a crash loop for the l7mp/stunner-auth-server deployment.

`exec ./manager: exec format error`

dissecting the image with skopeo I found that the manager binary is in amd64 format:

`$ file manager`
>manager: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=6UN65aHFAUKixp33-CoN/oSwKhOkw7WZ78NYcwY5O/XohG9sMgwCkz8WmKdzvi/IXPa-ErAPLdPREngQPy9, stripped

**Comment by levaitamas** [comment]
Hi @Daedaluz,
Thanks for letting us know! We truly appreciate it, since we have no apparatus for testing arm64 builds automatically. I will start investigating ASAP. One question: which version are you using: any stable or the `dev`?

**Comment by Daedaluz** [comment]
The version for this component is 0.17.0

Otherwise I just followed the instructions in the stunner repo with helm install

**Comment by levaitamas** [comment]
Pushed a quick fix. The CD pipeline just finished, and the `dev` version should be good now. I will ask around whether we can rebuild and republish the v0.17.0 image.

**Comment by Daedaluz** [comment]
Quick fix!
Thanks, I'll give it another try later today.

**Comment by Daedaluz** [comment]
I wrote a small Dockerfile to check contents:

Dockerfile:
```
FROM --platform=linux/amd64 l7mp/stunner-auth-server:dev AS data-dev-amd64
FROM --platform=linux/amd64 l7mp/stunner-auth-server:0.17.0 AS data-stable-amd64

FROM --platform=linux/arm64 l7mp/stunner-auth-server:dev AS data-dev-arm64
FROM --platform=linux/arm64 l7mp/stunner-auth-server:0.17.0 AS data-stable-arm64


FROM alpine:3.19
COPY --from=data-dev-amd64 / /data-dev-amd64
COPY --from=data-stable-amd64 / /data-stable-amd64

COPY --from=data-dev-arm64 / /data-dev-arm64
COPY --from=data-stable-arm64 / /data-stable-arm64

RUN apk add file
```

```
/ # file data-*/manager data-*/authd
data-stable-amd64/manager: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=6UN65aHFAUKixp33-CoN/oSwKhOkw7WZ78NYcwY5O/XohG9sMgwCkz8WmKdzvi/IXPa-ErAPLdPREngQPy9, stripped
data-stable-arm64/manager: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=6UN65aHFAUKixp33-CoN/oSwKhOkw7WZ78NYcwY5O/XohG9sMgwCkz8WmKdzvi/IXPa-ErAPLdPREngQPy9, stripped
data-dev-amd64/authd:      ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=O-0FN_QjdwMXdv8osH_p/EkflfOPGLzN-6xpG9zoT/wtRwrzLRXTTXXKK_E2qt/C-rLoEeTx9uyoDidqKxU, stripped
data-dev-arm64/authd:      ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=8hvmmcL9udJ42uzW4hi3/tMj7BFyLdBz89r4MO6RU/PxfCf7nTjPZ9ThzcplkD/gqVWI66J7PFogltjNpJn, stripped

```


apparently, the binary is called authd now, and it's still "manager" in the deployment as cmd together with some flags that are no longer present.

changing to authd instead, i get:
`13:38:02.365432 main.go:72: authd ERROR: Could not find CDS server: failed to query Kubernetes API server: pods is forbidden: User "system:serviceaccount:stunner-system:stunner-auth" cannot list resource "pods" in API group "" at the cluster scope`

obviously there is some additional changes done in dev.

Any pointers to how i go about testing dev?

**Comment by levaitamas** [comment]
Oh, I completely forgot about these recent breaking changes...  Sorry about that. 

Meanwhile, I managed to fire up the CD pipeline for the v0.17.0 image. It might take 10-15 minutes, but after that the stable version should work on arm64 too. Let me know if you encounter any issue.

**Comment by levaitamas** [comment]
Just wanted to mention, that the CD pipeline just finished and the [rebuilt 0.17.0 image](https://hub.docker.com/layers/l7mp/stunner-auth-server/0.17.0/images/sha256-153b93d9bec5973bb8ff00c2530c86ad29f214fcf6fc0dbe9636a19f4612f246?context=explore) is live on DockerHub.

**Comment by Daedaluz** [comment]
Can confirm that it's running now at least.
